experiment:
  name: VAE_stable
  base_path: /work3/s233249/ImgiNav/experiments/AEVAE_sweep/VAE_stable

dataset:
  manifest: /work3/s233249/ImgiNav/datasets/layouts.csv
  taxonomy_path: /work3/s233249/ImgiNav/ImgiNav/config/taxonomy.json
  batch_size: 32
  num_workers: 8
  seed: 42
  shuffle: true
  split_ratio: 0.9

model:
  type: vae
  in_channels: 3
  out_channels: 3
  base_channels: 64
  latent_channels: 4
  image_size: 512
  latent_base: 64
  norm: batch
  act: relu
  dropout: 0.0
  num_classes: null



training:
  epochs: 25
  lr: 0.0001
  log_interval: 10
  sample_interval: 100
  eval_interval: 1
  output_dir: /work3/s233249/ImgiNav/experiments/AEVAE_sweep/VAE_stable/output
  ckpt_dir: /work3/s233249/ImgiNav/experiments/AEVAE_sweep/VAE_stable/checkpoints

  loss:
    type: standard
    kl_weight: 0.000001
