# Experiment 4: RGB Reconstruction Only (Large Model)
# Input: 512x512x3 (layout images), Latent: 32x32x8

experiment:
  name: "exp4_rgb_only_large"
  save_path: "/work3/s233249/ImgiNav/experiments/NEW/exp4_rgb_only_large"

dataset:
  manifest: "/work3/s233249/ImgiNav/datasets/layouts.csv"
  outputs:
    rgb: "layout_path"  # Column name for layout RGB images
  filters:
    is_empty: [false]  # Filter out empty layouts
  return_path: false

autoencoder:
  encoder:
    in_channels: 3
    latent_channels: 8
    base_channels: 128  # Larger model
    downsampling_steps: 4  # 512 -> 256 -> 128 -> 64 -> 32
    activation: SiLU
    norm_groups: 8
  
  decoder:
    latent_channels: 8
    base_channels: 128  # Larger model
    upsampling_steps: 4  # 32 -> 64 -> 128 -> 256 -> 512
    activation: SiLU
    norm_groups: 8
    heads:
      - type: RGBHead
        name: rgb
        out_channels: 3
        final_activation: tanh

training:
  batch_size: 16
  num_workers: 8
  shuffle: true
  epochs: 100
  learning_rate: 0.0001
  optimizer: AdamW
  weight_decay: 0.01
  save_interval: 5  # Save checkpoint every 5 epochs
  sample_interval: 5  # Save sample images every 5 epochs
  
  loss:
    type: CompositeLoss
    losses:
      - type: L1Loss
        key: rgb
        target: rgb
        weight: 1.0

