# Experiment 5: RGB Reconstruction + Segmentation (Large Model)
# Input: 512x512x3, Latent: 32x32x8

autoencoder:
  encoder:
    in_channels: 3
    latent_channels: 8
    base_channels: 128  # Larger model
    downsampling_steps: 4  # 512 -> 256 -> 128 -> 64 -> 32
    activation: SiLU
    norm_groups: 8
  
  decoder:
    latent_channels: 8
    base_channels: 128  # Larger model
    upsampling_steps: 4  # 32 -> 64 -> 128 -> 256 -> 512
    activation: SiLU
    norm_groups: 8
    heads:
      - type: RGBHead
        name: rgb
        out_channels: 3
        final_activation: tanh
      - type: SegmentationHead
        name: segmentation
        num_classes: 10  # From rgb_to_class.yaml

