# experiment_config.yaml
dataset:
  room_manifest: "/work3/s233249/ImgiNav/datasets/room_dataset_with_emb.csv"
  scene_manifest: "/work3/s233249/ImgiNav/datasets/scene_dataset_with_emb.csv"
  data_mode: "rooms_only"     # "rooms_only" | "scenes_only" | "rooms_and_scenes"
  pov_type: "seg"          # "seg" | "tex" | null
  taxonomy_path: "/work3/s233249/ImgiNav/ImgiNav/config/taxonomy.json"
  batch_size: 8
  num_workers: 4
  seed: 42

model:
  latent_base: 64
  mixer: "mlp"                      # "linear" or "mlp"
  mixer_hidden_dim: 16000

  embedders:
    pov: "resnet18"
    graph: "sentence-transformers/all-MiniLM-L6-v2"

  autoencoder:
    config: "/work3/s233249/ImgiNav/experiments/VAE/VAE_512_64x64x4/autoencoder_config.yaml"
    ckpt: "/work3/s233249/ImgiNav/experiments/VAE/VAE_512_64x64x4/checkpoints/ae_epoch_40.pt"

  diffusion:
    scheduler: "cosine"             # "linear" or "cosine"
    num_steps: 500
    latent_channels: 4
    unet_config: "/work3/s233249/ImgiNav/ImgiNav/config/architecture/unets/medium_c.yml"

training:
  epochs: 10
  lr: 0.0001
  weight_decay: 0.01
  grad_clip: 1.0
  mixed_precision: true
  ema_decay: 0.999
  cond_dropout_pov: 0.1
  cond_dropout_graph: 0.1
  cond_dropout_both: 0.0
  use_modalities: "pov_only"            # "both" | "pov_only" | "graph_only" | "none"

  log_interval: 100
  eval_interval: 1000
  sample_interval: 2000
  eval_sample_num: 8

  ckpt_dir: "/work3/s233249/ImgiNav/experiments/Pipeline/exp1/checkpoints"
  output_dir: "/work3/s233249/ImgiNav/experiments/Pipeline/exp1/outputs"
