# --- Dataset ---
dataset:
  taxonomy_path: /work3/s233249/ImgiNav/ImgiNav/config/taxonomy.json
  manifest: /work3/s233249/ImgiNav/datasets/layouts.csv
  batch_size: 32
  split_ratio: 0.9
  num_workers: 4
  shuffle: true
  seed: 42

# --- Model ---
model:
  # input/output
  in_channels: 3          # 3 for RGB, 1 for grayscale, N for classes (one-hot)
  out_channels: 3          # same as input if RGB reconstruction
  image_size: 512
  latent_base: 64          # spatial size of latent feature map
  # capacity
  base_channels: 64        # first conv layer channels
  latent_channels: 4       # depth of latent tensor
  # normalization and activations
  norm: batch
  act: relu
  dropout: 0.0
  # decoder behavior
  use_sigmoid: false        # true for RGB+MSE, false for logits+CrossEntropy

# --- Training ---
training:
  epochs: 50
  lr: 1e-4
  kl_weight: 1e-6
  log_interval: 10
  sample_interval: 200
  eval_interval: 1
  output_dir: /work3/s233249/ImgiNav/experiments/VAE/cross_enth_loss/VAE_512_64x64x4/output
  ckpt_dir: /work3/s233249/ImgiNav/experiments/VAE/cross_enth_loss/VAE_512_64x64x4/checkpoints
  recon_loss: CrossEntropy   