# --- Dataset ---
dataset:
  taxonomy_path: /work3/s233249/ImgiNav/ImgiNav/config/taxonomy.json
  manifest: /work3/s233249/ImgiNav/datasets/layouts.csv
  batch_size: 64
  split_ratio: 0.9
  num_workers: 4
  shuffle: true
  seed: 42

# --- Model ---
model:
  # input/output
  in_channels: 3
  out_channels: 3
  image_size: 512
  latent_base: 64
  # capacity
  base_channels: 64
  latent_channels: 4
<<<<<<< HEAD
  num_classes: 13 # 
=======
  num_classes: 13 # <-- ADD THIS (Replace 25 with your actual number of classes)
>>>>>>> f8f80384cb79f60cde25ffe8b11907d9fd043b6e
  # normalization and activations
  norm: batch
  act: relu
  dropout: 0.0
  # decoder behavior
  use_sigmoid: false # <-- CHANGE THIS. SegmentationVAELoss uses MSE on RGB head

# --- Training ---
training:
  epochs: 50
  lr: !!float 1e-4
  log_interval: 10
  sample_interval: 200
  eval_interval: 1
  output_dir: /work3/s233249/ImgiNav/experiments/VAE/cross_enth_loss/VAE_512_64x64x4/output
  ckpt_dir: /work3/s233249/ImgiNav/experiments/VAE/cross_enth_loss/VAE_512_64x64x4/checkpoints
  
  # --- CORRECT LOSS CONFIG ---
  loss:
    type: segmentation
    kl_weight: !!float 1e-6
    lambda_seg: 1.0  # Weight for segmentation head loss
    lambda_mse: 1.0  # Weight for RGB reconstruction head loss
    taxonomy_path: /work3/s233249/ImgiNav/ImgiNav/config/taxonomy.json # Must be provided here
    include_background: true