dataset:
  batch_size: 64
  manifest: /work3/s233249/ImgiNav/datasets/layouts.csv
  num_workers: 8
  seed: 42
  shuffle: true
  split_ratio: 0.9
  taxonomy_path: /work3/s233249/ImgiNav/ImgiNav/config/taxonomy.json
model:
  type: ae
  in_channels: 3
  out_channels: 3
  base_channels: 64
  latent_channels: 4
  latent_base: 32
  image_size: 512
  act: relu
  norm: batch
  dropout: 0.2
  num_classes: 13
  use_sigmoid: true
training:
  epochs: 50
  eval_interval: 1
  log_interval: 10
  lr: 0.0001
  sample_interval: 200
  output_dir: /work3/s233249/ImgiNav/experiments/AEVAE_sweep/AE_dropout/output
  ckpt_dir: /work3/s233249/ImgiNav/experiments/AEVAE_sweep/AE_dropout/checkpoints
  loss:
    type: standard
    kl_weight: 0.0
    lambda_mse: 1.0
