encoder:
  in_channels: 3
  image_size: 512
  latent_dim: 4096
  latent_channels: 4
  latent_base: 32
  global_norm: null
  global_act: null
  global_dropout: 0.0
  layers:
    - out_channels: 48
      kernel_size: 3
      stride: 2
      padding: 1
      norm: batch
      act: relu
      dropout: 0.0
    - out_channels: 96
      kernel_size: 3
      stride: 2
      padding: 1
      norm: batch
      act: relu
      dropout: 0.0
    - out_channels: 192
      kernel_size: 3
      stride: 2
      padding: 1
      norm: batch
      act: relu
      dropout: 0.0

decoder:
  out_channels: 3
  image_size: 512
  latent_dim: 4096
  latent_channels: 4
  latent_base: 32