encoder:
  in_channels: 3
  image_size: 512
  latent_dim: 2048
  latent_channels: 8
  latent_base: 16
  global_norm: null
  global_act: null
  global_dropout: 0.0
  layers:
    - out_channels: 64
      kernel_size: 3
      stride: 2
      padding: 1
      norm: batch
      act: relu
      dropout: 0.0
    - out_channels: 128
      kernel_size: 3
      stride: 2
      padding: 1
      norm: batch
      act: relu
      dropout: 0.0
    - out_channels: 256
      kernel_size: 3
      stride: 2
      padding: 1
      norm: batch
      act: relu
      dropout: 0.0
    - out_channels: 384
      kernel_size: 3
      stride: 2
      padding: 1
      norm: batch
      act: relu
      dropout: 0.0
    - out_channels: 512
      kernel_size: 3
      stride: 2
      padding: 1
      norm: batch
      act: relu
      dropout: 0.0

decoder:
  out_channels: 3
  image_size: 512
  latent_dim: 2048
  latent_channels: 8
  latent_base: 16