dataset:
  manifest: /work3/s233249/ImgiNav/datasets/layouts.csv
  batch_size: 32
  split_ratio: 0.9
  num_workers: 4
  shuffle: true
  seed: 42

model:
  in_channels: 3          # RGB inputs
  out_channels: 3         # RGB reconstruction
  base_channels: 64       # starting conv channels
  latent_channels: 8      # channels in latent space
  image_size: 512         # input image size
  latent_base: 32         # spatial size of latent feature map
  norm: batch             # normalization type (batch, instance, or null)
  act: relu               # activation function
  dropout: 0.0            # dropout probability

training:
  epochs: 50
  lr: 0.0001
  kl_weight: 1e-6     
  log_interval: 10
  sample_interval: 200
  eval_interval: 1
  output_dir: /work3/s233249/ImgiNav/experiments/VAE/VAE_512_32x32x8
  ckpt_dir: /work3/s233249/ImgiNav/experiments/VAE/VAE_512_32x32x8/checkpoints
