# configs/diffusion.yaml

latent:
  base: 64          # spatial resolution of latent map (H = W = 64)
  channels: 4       # latent channels (C)

scheduler:
  type: CosineScheduler      # One of: LinearScheduler, CosineScheduler, SquaredCosineScheduler,
                             # SigmoidScheduler, ExponentialScheduler, QuadraticScheduler
  num_steps: 500

autoencoder:
  config: C:\Users\Hagai.LAPTOP-QAG9263N\Desktop\Thesis\repositories\ImagiNav\indexes\ae_configs\config_diff_4ch_64x64_vanilla.yml
  checkpoint: C:\Users\Hagai.LAPTOP-QAG9263N\Desktop\Thesis\repositories\ImagiNav\indexes\autoencoder_final_64x64x4_vanila\20251004-082051_ae_final\best.pt

unet:
  config: C:\Users\Hagai.LAPTOP-QAG9263N\Desktop\Thesis\repositories\ImagiNav\config\base_unet_medium.yml
  checkpoint: C:\Users\Hagai.LAPTOP-QAG9263N\Desktop\Thesis\repositories\ImagiNav\indexes\d_medium_500.pt
