dataset:
  manifest: "/work3/s233249/ImgiNav/datasets/layouts.csv"
  batch_size: 64
  split_ratio: 0.9
  num_workers: 4
  shuffle: true
  seed: 42

model:
  autoencoder_config: "/work3/s233249/ImgiNav/experiments/VAE/VAE_512_64x64x4/autoencoder_config.yaml"
  autoencoder_ckpt: "/work3/s233249/ImgiNav/experiments/VAE/VAE_512_64x64x4/checkpoints/ae_epoch_28.pt"
  latent_channels: 4         # must match autoencoder latent_channels
  base_channels: 64          # UNet width
  depth: 4                   # UNet depth (ensure 2^depth <= latent_base)
  time_dim: 256
  num_res_blocks: 
  scheduler: cosine          # cosine or linear
  num_steps: 1000
  norm: batch
  act: relu

training:
  epochs: 100
  log_interval: 1000
  eval_interval: 1000
  sample_interval: 1000
  checkpoint_interval: 10
  num_samples: 8
  grad_clip: 1.0
  output_dir: "/work3/s233249/ImgiNav/experiments/diffusion/diff_64x64x4_d4_t1000"
  ckpt_dir: "/work3/s233249/ImgiNav/experiments/diffusion/diff_64x64x4_d4_t1000/checkpoints"
