experiment:
  name: E5_Cosine_128
  base_path: /work3/s233249/ImgiNav/experiments/Diffusion_Uncond
dataset:
  manifest: /work3/s233249/ImgiNav/datasets/layouts.csv
  split_ratio: 0.9
  seed: 42
  batch_size: 32
  num_workers: 8
  shuffle: true
  taxonomy_path: /work3/s233249/ImgiNav/ImgiNav/config/taxonomy.json
model:
  autoencoder:
    config: /work3/s233249/ImgiNav/experiments/AEVAE_sweep/AE_large_latent_seg/output/autoencoder_config.yaml
    checkpoint: /work3/s233249/ImgiNav/experiments/AEVAE_sweep/AE_large_latent_seg/checkpoints/ae_latest.pt
  diffusion:
    scheduler:
      type: cosine
      num_steps: 1000
    unet:
      type: dualunet
      in_channels: 4
      out_channels: 4
      base_channels: 128
      depth: 4
      num_res_blocks: 2
      time_dim: 128
      cond_channels: 0
      act: relu
      norm: batch
      dropout: 0.1
      fusion_mode: none
      cond_mult: 1.0
training:
  epochs: 50
  log_interval: 100
  eval_interval: 1000
  sample_interval: 2000
  grad_clip: 1.0
  num_samples: 8
  output_dir: /work3/s233249/ImgiNav/experiments/Diffusion_Uncond\E5_Cosine_128\output
  ckpt_dir: /work3/s233249/ImgiNav/experiments/Diffusion_Uncond\E5_Cosine_128\checkpoints
