#!/bin/bash
# Launch script for adversarial training pipeline
# Submits adversarial training job with configurable parameters

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_DIR="${SCRIPT_DIR}/logs"

# Ensure log directory exists
mkdir -p "${LOG_DIR}"

echo "=========================================="
echo "Launching Adversarial Training Pipeline"
echo "=========================================="
echo ""
echo "This pipeline will:"
echo "  1. Generate fake latents from current diffusion model (full T-step sampling)"
echo "  2. Train discriminator on real vs fake latents"
echo "  3. Fine-tune diffusion with discriminator loss using gradient reconnection"
echo "  4. Repeat for configurable number of iterations"
echo ""
echo "Note: Each iteration trains a NEW discriminator from scratch."
echo "      The discriminator is trained to distinguish between:"
echo "      - Real latents (from dataset)"
echo "      - Fake latents (generated by current diffusion model)"
echo ""
echo "Log directory: ${LOG_DIR}"
echo ""

# Submit job
echo "Submitting adversarial training job..."
OUTPUT=$(bsub < "${SCRIPT_DIR}/run_adversarial_training.sh" 2>&1)

if [[ $? -eq 0 ]]; then
    JOBID=$(echo "$OUTPUT" | grep -oP '<\d+>' | tr -d '<>')
    echo "  ✓ Job submitted: $JOBID"
    echo ""
    echo "=========================================="
    echo "Job submitted successfully!"
    echo "=========================================="
    echo "Job ID: $JOBID"
    echo ""
    echo "Monitor with:"
    echo "  bjobs $JOBID"
    echo "  bjobs -u $USER"
    echo ""
    echo "Check logs:"
    echo "  ${LOG_DIR}/adversarial_training.${JOBID}.out"
    echo "  ${LOG_DIR}/adversarial_training.${JOBID}.err"
    echo ""
    echo "To cancel:"
    echo "  bkill $JOBID"
    echo ""
else
    echo "  ✗ Failed to submit"
    echo "$OUTPUT"
    exit 1
fi

